# company autodl
mode: MY
local:
    root_dir: 'D:\workspace\data\dl\eye_com'
    class_file: 'D:\workspace\data\dl\flower\flower.json'
    pre_weight_path: 'D:\workspace\data\training_data\resnet50\resnet50-acc76.264.pth'
    save_root: 'D:\workspace\data\training_data'
MY:
    root_dir: '/home/8TDISK/weihule/data/eye_competition'
    class_file: 'D:\workspace\data\dl\flower\flower.json'
    pre_weight_path: '/home/8TDISK/weihule/data/training_data/resnet50/resnet50-acc76.264.pth'
    save_root: '/home/8TDISK/weihule/data/training_data/resnet50_multi_Pattern'

autodl:
    root_dir: '/root/autodl-tmp/imagenet100'
    class_file: 'D:\workspace\data\dl\flower\flower.json'
    pre_weight_path: '/root/autodl-nas/classification_data/resnet/pths/resnet50_imagenet100_acc56.pth'
    save_root: '/root/autodl-nas/classification_data/resnet'

# train_csv: 'D:\workspace\data\dl\eye_com\Train\Train.csv'
train_csv: '/home/8TDISK/weihule/data/eye_competition/Train/Train.csv'

# model
backbone_type: resnet50
num_classes: 14

# dataset
dataset_name: eye
train_set_name: train
val_set_name: val
image_size: 224
mean:
    - 0.485
    - 0.456
    - 0.406
std:
    - 0.229
    - 0.224
    - 0.225

# data
seed: 0
epochs: 15
batch_size: 64
lr: 0.004
weight_decay: 0.00004
momentum: 0.9
lrf: 0.001
num_workers: 4
freeze_layer: False
apex: False
# 日志记录频率, 如为10, 即一个epoch内, 遍历循环10次train_loader就记录日志
print_interval: 50
# 保存频率, 如为1, 即一个epoch保存一次checkpoints
save_interval: 1

# optimizer scheduler
step_size: 10
gamma: 0.1

device: cuda