# company autodl
mode: local
data_loc:
    local:
        root_dir: 'D:\workspace\data\dl\flower'
        class_file: 'D:\workspace\data\dl\flower\flower.json'
        pre_weight_path: 'D:\Desktop\resnet50-acc76.264.pth'
        save_root: 'E:\workspace\classification\resnet50'

    autodl:
        root_dir: '/root/autodl-tmp/imagenet100'
        class_file: 'D:\workspace\data\dl\flower\flower.json'
        pre_weight_path: '/root/autodl-nas/classification_data/resnet/pths/resnet50_imagenet100_acc56.pth'
        save_root: '/root/autodl-nas/classification_data/resnet'

# model
backbone_type: resnet50
num_classes: 5

# dataset
dataset_name: flower5
train_set_name: train
val_set_name: val
image_size: 224
mean:
    - 0.485
    - 0.456
    - 0.406
std:
    - 0.229
    - 0.224
    - 0.225

# data
seed: 0
epochs: 15
batch_size: 8
lr: 0.001
lrf: 0.001
num_workers: 4
freeze_layer: False
apex: False
print_interval: 50
save_interval: 1

# optimizer scheduler
step_size: 10
gamma: 0.1
T_max: 15

device: cuda